import os
import pandas as pd
from openai import OpenAI

client = OpenAI()


def generate_ai_news():
    df = pd.read_csv("data/human/human_news.csv")
    all_ai_paragraphs = []

    #introducem promptul, sursa: https://pypi.org/project/openai/
    for paragraph in df["content"]:
        word_count = len(str(paragraph).split())
        
        completion = client.chat.completions.create(
            model = "gpt-5.2",
            messages = [
                {"role" : "user", "content" : f""" 
                You are a writing assistant.
                
                Write an original news-style paragraph similar in tone, structure, and topic to the text below.
                
                Target length: approximately {word_count} words (±20%).
                
                Use a neutral, journalistic style.
                Do not copy phrases or sentences from the original text.
                Do not mention that this text was generated by an AI.
                Return only the generated article.
                
                ORIGINAL HUMAN NEWS ARTICLE:
                {paragraph}
                """}
            ]
        )
        
        ai_paragraph = completion.choices[0].message.content
        all_ai_paragraphs.append(ai_paragraph)
        
    #creare fisier csv pentru paragrafe de news generate de ai, cream initial dictionarul pentru df
    pd.DataFrame({"content": all_ai_paragraphs}).to_csv("data/ai/ai_news.csv", index = False)
    print("S-a generat fisierul")
    
    
    
    
def generate_ai_reviews():
    df = pd.read_csv("data/human/human_reviews.csv")
    all_ai_paragraphs = []

    for paragraph in df["review"]:
        word_count = len(str(paragraph).split())
        
        #sursa: https://pypi.org/project/openai/
        completion = client.chat.completions.create(
            model = "gpt-5.2",
            messages = [
                {"role" : "user", "content" : f""" 
                You are a writing assistant.
                
                Write an original product review in natural, human-like language.
                The review should be similar in tone, style, and topic to the text below.
                
                Target length: approximately {word_count} words (±20%).
                
                Do not copy phrases or sentences from the original text.
                Do not mention that this text was generated by an AI.
                Return only the generated review.
                
                ORIGINAL HUMAN REVIEW:
                {paragraph}
                """}
            ]
        )
        
        ai_paragraph = completion.choices[0].message.content
        all_ai_paragraphs.append(ai_paragraph)
        
    #creare fisier csv pentru paragrafe de reviews generate de ai, cream initial dictionarul pentru df
    pd.DataFrame({"content": all_ai_paragraphs}).to_csv("data/ai/ai_reviews.csv", index = False)
    print("S-a generat fisierul")
    
    
    
    
    
def generate_ai_informative():
    df = pd.read_csv("data/human/human_informative.csv")
    all_ai_paragraphs = []

    for paragraph in df["content"]:
        word_count = len(str(paragraph).split())
        
        #sursa: https://pypi.org/project/openai/
        completion = client.chat.completions.create(
            model = "gpt-5.2",
            messages = [
                {"role" : "user", "content" : f""" 
                You are a writing assistant.

                Write an original informative text in clear, human-like language.
                The text should be similar in tone, style, and topic to the text below.

                Target length: approximately {word_count} words (±20%).

                Use an explanatory and neutral style.
                Focus on clearly presenting information and concepts.
                Do not copy phrases or sentences from the original text.
                Do not mention that this text was generated by an AI.
                Return only the generated text.

                ORIGINAL HUMAN INFORMATIVE TEXT:
                {paragraph}

                """}
            ]
        )
        
        ai_paragraph = completion.choices[0].message.content
        all_ai_paragraphs.append(ai_paragraph)
        
    #creare fisier csv pentru paragrafe informative generate de ai, cream initial dictionarul pentru df
    pd.DataFrame({"content": all_ai_paragraphs}).to_csv("data/ai/ai_informative.csv", index = False)
    print("S-a generat fisierul")
    
    
    
    
    
def main():
    #generate_ai_news()
    #generate_ai_reviews()
    generate_ai_informative()
    
    
    
if __name__ == "__main__":
    main()  